#
# This is default Thoth configuration file placed in a root of a repo. Please adjust values listed below.

host: stage.thoth-station.ninja
tls_verify: false

requirements_format: pipenv

runtime_environments:
  - name: "fedora:29"
    recommendation_type: LATEST
    operating_system:
      name: fedora
      version: "29"
